#!/bin/sh
#
# Gradle start up script for POSIX generated by Gradle
#

APP_HOME=$(dirname "$0")
JAVA_HOME="${JAVA_HOME:-$HOME/jdk17/Contents/Home}"
export JAVA_HOME

exec "$JAVA_HOME/bin/java" \
  -classpath "$APP_HOME/gradle/wrapper/gradle-wrapper.jar" \
  org.gradle.wrapper.GradleWrapperMain "$@"
